{application,proxima,
             [{description,"Experimental elastic HTTP proxy"},
              {vsn,"1.0"},
              {registered,[]},
              {applications,[kernel,stdlib,riak_core]},
              {mod,{proxima_app,[]}},
              {env,[]},
              {modules,[default_handler,proxima,proxima_app,proxima_http,
                        proxima_http_client,proxima_sup,proxima_vnode,
                        proxima_vnode_dispatcher]}]}.
